### ISSUE TITLE
Removing a channel

### ISSUE THREAD

**Issue by mpschr** [whitews/FlowIO#1]
Hi

I am looking for manipulating a certain amount of channels from an .fcs file. I am reading to the code and it is not entirely clear to me how I would proceed to do that using your library. Is it possible ? 

Thanks in advance!

**Comment by mpschr** [comment]
Hi again

I think I figured it out. Just letting you and anybody wondering the same know.

Assuming I want to delete 10 channels with indices 4,6,8,9,10 in file test.fcs, I did the following. It works in technical terms. Maybe you can have a look if there is something important to the integrity of the data that I did not take into account

```
t = flowio.FlowData('test.fcs')
n = np.reshape(t.events, (-1, t.channel_count))

names = {int(k): t.channels[k]['PnN'] for k,v in t.channels.items()}.values()
names = list(names)
optional_names = {int(k): t.channels[k]['PnS'] if 'PnS' in t.channels[k] else None for k,v in t.channels.items()}.values()
optional_names = list(optional_names)

candidates_indices = sorted([4,6,8,9,10],reverse=True)

for i in candidate_indices:
    del names[i]
    del optional_names[i]    
    n = np.delete(n,i,1)

newdata = n.flatten().tolist()

fh = open('test.removed.fcs', 'wb')
flowio.create_fcs(newdata, names, fh, opt_channel_names=optional_names)
fh.close()
```

**Comment by whitews** [comment]
Hi Michael,

Yes, that looks reasonable, glad you were able to figure it out. My only comment would be to take care when removing fluorescence columns on uncompensated data. Once removed the resulting FCS file can no longer be properly compensated. The solution for this would be to save the compensated data with the channels filtered. I have another library FlowUtils that contains functions for compensating and transforming data.

Regards,
Scott
