### ISSUE TITLE
Open files containing multiple datasets

### ISSUE THREAD

**Issue by JcGKitten** [whitews/FlowIO#15]
Hey,

The current release doesn't allow users to choose which dataset they want to load if a file contains multiple datasets or am I missing something?

It seems like all the functions are already ready to read a selected dataset, but there is no check for the `nextdata` keyword to recognize if there is more then one dataset available.
I could try to open a pull request for this, but wanted to check in with you first.

Best wishes 
Max

**Comment by whitews** [comment]
Hey Max,

You must have followed the request from David Ng (@davidpng) on the flowkit issue ;)

Yes, if you want to tackle adding multiple data sets via the `nextdata` keyword, give it a shot! I discussed this with David in email correspondence and my initial plan to handle this was:

> a FlowIO utility function that takes one of these as input and returns a list of FlowData instances. This would allow me to throw an error from the FlowData constructor that would propagate to the FlowKit Sample class, and that error would indicate to use the new FlowIO utility function. Once you have a list of FlowData instances you can export them as new FCS files for consumption in FlowKit or any other library.

I __think__ this is a better approach than adding an argument to the FlowData constructor to choose the data set to use for the FlowData instance. We can discuss the rationale for that in more detail if you want. The issue with this method is the replication of byte-parsing code in the new function and the FlowData methods. Those methods could be refactored out to common utility functions used by both.

If you want to give it a shot, create a new branch off of `develop`. One requirement is not to add any external dependencies, I try to keep FlowIO as light as possible.

Thanks,
Scott

**Comment by JcGKitten** [comment]
Hey Scott, 
my first plan/ idea was to stick with the flowCore behavior and throw a warning that multiple datasets where found and load the first one. But your approach sounds good, but looks like a bigger operation.
I'm not even sure if this is a common case with .fcs files, I only found on till now and I'm not sure if I would be allowed to upload it as a test case. Is it ok if I tell you next week, whether I try to solve this task? I will be away the next couple of days.

Have a nice weekend,
Max

**Comment by whitews** [comment]
Hey Max,

No worries, don't feel obligated in any way to take it on. I won't have time before next week to get to it either. Think about it and let me know next week.

You have a great weekend as well!
-Scott

**Comment by JcGKitten** [comment]
Hey Scott,

I won't be able to take the task now, but I will check in if it still needs to be solved, when there is more time.
But maybe it's good that your plans are documented here now, if someone else want to take over.
If my bosses give me the time to write the pull request, I will let you know.

Best wishes,
Max

**Comment by whitews** [comment]
Closing as this is now in master thanks to Max
