### ISSUE TITLE
Incorrect estimation of data_stop

### ISSUE THREAD

**Issue by cchrysosdtx** [whitews/FlowIO#25]
I am using flowio to parse an FCS 3.0 file generated from the iQue. When I use flowio to parse the file, no event data is returned even though there are 72374 events across 32 channels. Looking at the code I believe it is because in the metadata of the fcs, end_data = begin_data which makes the estimation of data_start and data_stop for function `__calc_data_item_count` incorrect. If instead I had data_stop to be equal to data_start + event_count * num_channels *4 - 1 then I am able to correctly read out event data. Also when using FCSParser, it produces the expected behavior. 

Is this and edge case scenario, and if so, there someway to account for this via a parameter (i.e. estimate data_stop from events) or am I non instantiating the object correctly.

**Comment by whitews** [comment]
Hi,

It sounds like you are describing an FCS file with incorrect data offset values in the TEXT section. Do you get any errors or warnings trying to create a FlowData object?

There are 2 places where the data offsets are stored in an FCS file, you can read about this and some options in the docs here:

https://flowio.readthedocs.io/en/latest/api.html#flowio.FlowData

If the file loads as you indicate but there are no events, I'd be interested to see the output of the `header` and `text` attributes. Could you post these (removing any sensitive info)? Or if you are willing to share the file privately I'm happy to have a look.

Thanks,
Scott

**Comment by cchrysosdtx** [comment]
I don't think its incorrect offset in the text section because text can be parsed correctly? As I mentioned if I force datastop parameter based on data start and data start + num_events * num_channels - 1 (extracted from text)  I get correct values without any parsing errors. 

Here is the header:

```
{'version': '3.0',
 'text_start': 58,
 'text_stop': 6265,
 'data_start': 6266,
 'data_stop': 6266,  # this is what I think is causing the issue
 'analysis_start': 0,
 'analysis_stop': 0}
 ```
 
 Here is a snippet of some text fields 
 ```
 {
  'op': 'Admin',
 'smno': 'A01',
 'datatype': 'F',
 'mode': 'L',
 'byteord': '4,3,2,1',
 'nextdata': '0',
 'par': '32',
 'p1b': '32',
 'p2b': '32',
 'p3b': '32',
 'p4b': '32',
 'p5b': '32',
 'p6b': '32',
 'p7b': '32',
 'p8b': '32',
 'p9b': '32',
 'p10b': '32',
 'p11b': '32',
 'p12b': '32',
 'p13b': '32',
 'p14b': '32',
 'p15b': '32',
 'p16b': '32',
 'p17b': '32',
 'p18b': '32',
 'p19b': '32',
 'p20b': '32',
 'p21b': '32',
 'p22b': '32',
 'p23b': '32',
 'p24b': '32',
 'p25b': '32',
 'p26b': '32',
 'p27b': '32',
 'p28b': '32',
 'p29b': '32',
 'p30b': '32',
 'p31b': '32',
 'p32b': '32',
 'p1r': '16777216',
 'p2r': '16777216',
 'p3r': '16777216',
 'p4r': '16777216',
 'p5r': '16777216',
 'p6r': '16777216',
 'p7r': '16777216',
 'p8r': '16777216',
 'p9r': '16777216',
 'p10r': '16777216',
 'p11r': '16777216',
 'p12r': '16777216',
 'p13r': '16777216',
 'p14r': '16777216',
 'p15r': '16777216',
 'p16r': '16777216',
 'p17r': '16777216',
 'p18r': '16777216',
 'p19r': '16777216',
 'p20r': '16777216',
 'p21r': '16777216',
 'p22r': '16777216',
 'p23r': '16777216',
 'p24r': '16777216',
 'p25r': '16777216',
 'p26r': '16777216',
 'p27r': '16777216',
 'p28r': '16777216',
 'p29r': '16777216',
 'p30r': '16777216',
 'p31r': '16777216',
 'p32r': '16777216',
 'cyt': 'IntelliCyt iQue3', 
 'timestep': '0.005',
 'beginstext': '0000000058',
 'endstext': '0000011245',
 'enddata': '0000006266',
 'begindata': '0000006266',
 'beginanalysis': '0',
 'endanalysis': '0',
 'fil': 'IntelliCyt_iQue3.fcs',
 'iccompensation': 'Empty'}
 ```

**Comment by whitews** [comment]
OK, this explains what is happening. The `enddata` offset reported is incorrect, as the data start and data end byte locations cannot be the same location if there is actually event data in the file.

**Comment by cchrysosdtx** [comment]
Yes I agree, thats what I was trying to explain with regard to an edge case. So in this instance is there some way we can provide a parameters to ignore the dependency on data stop metadata and instead infer it from number of events and channels? As I mentioned FCSParser appears to always only use num events and channels.

**Comment by whitews** [comment]
I'd definitely consider a PR for this. I don't want to complicate the constructor signature any further for non-compliant files, so this would have to avoid adding another option.

**Comment by cchrysosdtx** [comment]
OK I'll see if I have some time to formulate some options but I would also mention that these are files straight from an ique so I am not sure if they would be considered "non-compliant"? In the meantime, I'll take a look at the ique export and see if there is something funky going from that end.

**Comment by whitews** [comment]
If the iQue system is creating these files with incorrect data offsets, I'd followup with their technical support. It makes no sense that the data start and end offsets could be the same for a file with event data.
