### ISSUE TITLE
Question about flow cytometry data 

### ISSUE THREAD

**Issue by niloofar78** [whitews/FlowIO#28]
I have some flow cytometry data with LMD format Is it possible to work with them in python using Flowio or I should look for another library
Thanks for helping me

**Comment by whitews** [comment]
Hi,

FlowIO is intended for basic reading and writing of FCS files. You are likely better suited to use the higher level FlowKit library that I also maintain. The Sample class in FlowKit reads in a FCS file and applies the proper pre-processing using the metadata in the file. You will also get more user-friendly access to the event data via NumPy arrays or Pandas DataFrames.

https://github.com/whitews/FlowKit

Kind regards,
Scott
