### ISSUE TITLE
Issue loading fcs files

### ISSUE THREAD

**Issue by sjkdenny** [whitews/FlowIO#3]
I'm just starting to look into implementing a python-based interpretation of fcs files using flowkit. However, I'm having trouble right at the beginning, with flowIO unable to load the fcs files I'm working with. 
I'm getting the warning `UserWarning: text in segment does not start and end with delimiter
  warn("text in segment does not start and end with delimiter")`

and later:
```
error                                     Traceback (most recent call last)
<ipython-input-5-bca60f0715fe> in <module>
----> 1 fd = flowio.FlowData('G11.fcs')

~/anaconda2/envs/analyzefacsmore/lib/python3.6/site-packages/flowio/flowdata.py in __init__(self, filename)
     81             d_start,
     82             d_stop,
---> 83             self.text)
     84
     85         try:

~/anaconda2/envs/analyzefacsmore/lib/python3.6/site-packages/flowio/flowdata.py in __parse_data(self, offset, start, stop, text)
    192                 stop,
    193                 data_type.lower(),
--> 194                 order)
    195         else:  # ascii
    196             data = self.__parse_ascii_data(

~/anaconda2/envs/analyzefacsmore/lib/python3.6/site-packages/flowio/flowdata.py in __parse_float_data(self, offset, start, stop, data_type, order)
    256
    257         tmp = unpack('%s%d%s' % (order, num_items, data_type),
--> 258                      self.__read_bytes(offset, start, stop))
    259         return tmp
    260

error: unpack requires a buffer of 277676 bytes
```

I'm consistently getting this error for all the fcs files we are producing (an Attune, not sure the software version). The flowIO load works great for an example fcs file in the flowKit example. 

I uploaded one file as an example. 
[issue_file.zip](https://github.com/whitews/FlowIO/files/4969979/issue_file.zip)

**Comment by whitews** [comment]
Thanks for reporting this and for including an example file. I'll have a look and let you know what I find.

**Comment by dcroote** [comment]
In case it helps, I also see this error with v3.0 and v3.1 fcs files exported from a Sony SH800S

**Comment by whitews** [comment]
Thanks Derek,

I believe I have found the issue, but need to make sure the fix doesn't impact reading other FCS files. I should have an updated release with the fix this week.

**Comment by whitews** [comment]
@sjkdenny @dcroote 

I've fixed the issue reading these files in the latest version of FlowIO (version 0.9.6). If you could, please verify the latest version resolves the issue, and if not I will re-open. Thanks again for submitting the bug report!

**Comment by dcroote** [comment]
Works now for both v3.0 and v3.1 fcs files on my end! Thanks @whitews
