### ISSUE TITLE
Parsing an FCS file with variable int sizes fails raises an exception (and it could parse much faster)

### ISSUE THREAD

**Issue by matt-faria** [whitews/FlowIO#9]
When parsing an FCS file that contains int data with variable lengths, this line raises an exception in Python3: 
https://github.com/whitews/FlowIO/blob/51d10fb6ad62660f5a56c32305412b540fb88c09/flowio/flowdata.py#L259
as a map is not subscriptable. Possibly a holdover from converting from Python 2-3 ?

OS: windows, but should happen on everything.  

This is pretty easy to fix; but a secondary issue is that parsing each value individually is very slow (multiple minutes for a decent sized file). I've got a fix for both (which also simplifies that part of the code); will make a pull request!

**Comment by whitews** [comment]
Hey Matt,

Funny you found this as I just fixed that in the 0.9.9 release (converting the map iterator to a list). I forgot to push my local changes to the git repo but it is in the PyPI release, but the changes are there now so you might need to merge them into your branch. 

Anyway, the variable length code is something I've long suspected but didn't have an FCS sample to properly test (thanks for the example!). Not sure how that map bug originated...FlowIO, FlowUtils, and FlowStats were all created from the original fcm package I inherited years ago. Nice to see FlowIO getting a fresh pair of eyes.

I'll review your latest PR and get back to you later today.

**Comment by whitews** [comment]
Hi Matt,

Your PR has been merged. The additions in PR were incompatible with Python 2, but I decided it was time to drop Python 2 support since it is EOL. FlowIO 0.9.10 has been released with the new bug fix.

Thanks again, your recent contributions are much appreciated!

**Comment by matt-faria** [comment]
Glad to hear it and happy to help!
